- fixed the spnavd_x11 script to make error reporting more extensive, and the   messages more reasonable. (fix contributed by: Doug LaRue).
git-svn-id: svn+ssh://svn.code.sf.net/p/spacenav/code/spacenavd@6 ef983eb1-d774-4af8-acfd-baaf7b16a646

diff --git a/spnavd_x11 b/spnavd_x11
--- a/spnavd_x11
+++ b/spnavd_x11
@@ -28,7 +28,15 @@ fi
 pid="`pidof spacenavd`"
 if [ -n "$pid" ]; then
 	kill $sig $pid
-	echo "signalled spacenavd, it should now start sending X events."
+	if [ $? = 0 ]; then
+		if [ $sig = '-usr1' ]; then
+			echo "signalled spacenavd, it should now start sending X events."
+		else
+			echo "signalled spacenavd, stopped sending X events."
+		fi
+	else
+		echo "sending signal to spacenavd failed."
+	fi
 else
 	echo "spacenavd daemon is not running, nothing to do."
 fi
